### ISSUE TITLE
Will backups still work if I'm using Cronopete on a mainly headless setup?

### ISSUE THREAD

**Issue by Basilmir** [rastersoft/cronopete#11]
I am looking for a backup solution for my Raspberry Pi 2 server. Is has Raspbian but it doesn't "startx" unless I log in and start it myself when I need it.

If I setup Cronopete and then just never "startx" will it continue to work in the background?

**Comment by rastersoft** [comment]
It is not possible because you need a desktop. But it should be possible to use the class "backup" to create a command-line version. In fact, originally cronopete was a pure command line program.

**Comment by puccaso** [comment]
you could VNC into your device?

**Comment by rastersoft** [comment]
If you can VNC, then you have a graphical environment...
