### ISSUE TITLE
Will backing up to a Airport Time Capsule "network share" running HFS+ work (they do support hard links)?

### ISSUE THREAD

**Issue by Basilmir** [rastersoft/cronopete#12]
With the use of hard drives in Airport Extreme routers, either connected via USB and shared on the network or built into the router as in the case of an Airport Time Capsule backing up to a network share that can use hard links should should be possible. The disks have to be HFS+ so hard links are used. Is this supported with Cronopete?

**Comment by rastersoft** [comment]
Currently cronopete only supports locally connected hard disks. I hope to have some spare time in the future for adding support for remote backup.

**Comment by ProfElectric** [comment]
Have you been able to make any progress on this?  Didn't want to create clutter and open a new issue when it's not.  If you're still investigating git file structure, there is a program called bup (available here on github) which has a modified git structure better suited for large files, in case you weren't aware.

**Comment by rastersoft** [comment]
Hi. No, unfortunately I've been quite busy.
