### ISSUE TITLE
Backup device not available, Aborting backup.

### ISSUE THREAD

**Issue by robertlight** [rastersoft/cronopete#13]
I've installed cronopete (using apt) and the GUI works but when I try to start a backup, I get (at the bottom)... "Backup device not available, Aborting backup"

I've tried to unmount the disk, reformat it, mount it, then specify the disk via configure dialog.

nothing seems to work.

**Comment by rastersoft** [comment]
Can you kill cronopete and launch it again from a command line, and check if it shows something there? Also, can you check the LOG tab, in the configuration window?

**Comment by robertlight** [comment]
It apparently remounts the disk read-only....therefore it can't write to the device.

**Comment by rastersoft** [comment]
Mmmm... What operating system are you using? Which version?

**Comment by robertlight** [comment]
ubuntu (actually mint) 
uname -a:
Linux light-E6530 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by robertlight** [comment]
I can't seem to get my filesystem to mount writeable

**Comment by rastersoft** [comment]
Mmmm... with that kernel version, I suspect you are using an old version (this is: that Mint version isn't based on Ubuntu 14.10; maybe in 14.04?)

Current versions of Cronopete should be able to format the disk and set the permissions...

Try to do this: open a terminal, and type:

    chown XXXX /dev/your_hard_disk

being "XXXX" your username, and /media/your_hard_disk the mount point of the external hard disk (probably /media/usb1). Then, try again to backup.

**Comment by rastersoft** [comment]
Ok, confirmed: last version of Linux Mint is based on Ubuntu 14.04, not 14.10. That means that you are using an old version of cronopete.

**Comment by robertlight** [comment]
cronopete doesn't output any error messages (to stdout)

**Comment by robertlight** [comment]
which version of cronopete should I be using?

**Comment by robertlight** [comment]
here's my system info:
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/

**Comment by rastersoft** [comment]
You should be using cronopete 3.18.4.

Be sure that you have ONLY udisks2 installed, and not udisks.

**Comment by robertlight** [comment]
how do I check whether I have udisks or udisks2??
I'm running cronopete 3.18.4

**Comment by robertlight** [comment]
looks like I had udisks as well as udisks2 installed.   Just removed udisks.
Should I reboot?
should I restart cronopete?

**Comment by rastersoft** [comment]
Try to reboot... just in case

**Comment by robertlight** [comment]
I rebooted... cronopete (I assume) announced that it would begin backup as soon as my disk device was available.    The disk mounted but it mounted RO

**Comment by rastersoft** [comment]
It seems that you are formating your disk with permissions for only root... But in theory, cronopete should detect it and offer to format the disk.

Try to connect another disk, choose it in cronopete, and then choose again the original; that should trigger the format... Meanwhile, I will try to fix this.

**Comment by robertlight** [comment]
it looks like when the USB drive is plugged in it is owned by root.  getfacl shows:
getfacl: Removing leading '/' from absolute path names
# file: media/light/8282ef1d-77ee-468c-bf9e-ad15843b68ba
# owner: root
# group: root
user::rwx
group::r-x
other::r-x

**Comment by rastersoft** [comment]
What do you do to format the disk? Do you use command line, or gnome-disks?

**Comment by robertlight** [comment]
I was using the "Disks" utility.   Somehow I am not the owner of the disk.  How do I format the disk and might my user the owner?

**Comment by robertlight** [comment]
I don't know if this will help.... but I changed my filesystem from ext4 to NTFS and now I can mount the partition writeable.

the problem now is that cronopete can't see the disk in the configure screen

**Comment by rastersoft** [comment]
Mark the option "Show all disks", and ensure that the disk is mounted.

**Comment by robertlight** [comment]
the checkbox is checked, the disk is mounted (and is writeable)

**Comment by robertlight** [comment]
getting:
** (cronopete:6024): CRITICAL **: file /build/buildd/cronopete-3.18.4/build_dir/src/choose.c: line 3043: uncaught error: Error getting filesystem info: Input/output error (g-io-error-quark, 0)

**Comment by rastersoft** [comment]
Ops... That doesn't look good. I'll check the sources. Give me a moment...

**Comment by rastersoft** [comment]
It seems a problem with UDISKS2... I suspect there is a problem with permissions in your system.

**Comment by rastersoft** [comment]
I uploaded a version with some debug code. Can you download the GITHUB repo and compile it in your system?

**Comment by rastersoft** [comment]
I uploaded a new DEB package with what I think should fix this. Until it is published in the PPA, you can download it from https://launchpad.net/~rastersoft-gmail/+archive/ubuntu/cronopetedev/+build/7348173 .

**Comment by rastersoft** [comment]
It seems it is published. A simple update should add it.

**Comment by rastersoft** [comment]
Did you try it? Did it work?
