### ISSUE TITLE
Crash with 'double free or corruption' reported

### ISSUE THREAD

**Issue by jforissier** [rastersoft/cronopete#14]
cronopete version 3.18.5 (Vivid package, 64-bit) crashes. Dialog box reports:

- AssertionMessage
```
*** Error in `cronopete': double free or corruption (fasttop): 0x0000000002323cd0 ***
```
- StacktraceTop
```
__libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fb3fe3df1a8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
malloc_printerr (ptr=<optimized out>, str=0x7fb3fe3df270 "double free or corruption (fasttop)", action=1) at malloc.c:4965
_int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3834
__GI__libc_free (mem=<optimized out>) at malloc.c:2950
usbhd_backend_get_drive_path ()
```

**Comment by rastersoft** [comment]
Yes, I received it now... I'll check it.

**Comment by rastersoft** [comment]
This is odd: when running cronopete from command line "as is", I receive that error sometimes, after several hours running; but when running it with valgrind, it doesn't fail :?

**Comment by rastersoft** [comment]
I recreated the debian, ubuntu and fedora packages, just in case it was a bug in the vala compiler. Try them again, please.

**Comment by jforissier** [comment]
Thanks for looking into this. FYI, the problem has not occurred again for the last several days. Hopefully, the bug went away with some other package updates. Previously it would happen quite often.

**Comment by rastersoft** [comment]
I also suspect that the problem is elsewhere, because, with valgrind, I detect an use of a non-initialized memory zone, but it is inside GLib's GIO.
