### ISSUE TITLE
Not work Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ElvisPresly** [rastersoft/cronopete#18]
doesn't work and it is very sad. It is the best program which I have found under Linux
![2016-04-27 09-31-46](https://cloud.githubusercontent.com/assets/18265958/14843682/f65f1550-0c5a-11e6-8abd-bae519bcdd80.png)

**Comment by rastersoft** [comment]
Could you, please, give more hints? Why doesn't it work? What messages do you receive when installing or launching?

**Comment by ElvisPresly** [comment]
In a package installation time, it asks dependence "libgslOldbl"
I haven't found her in standard repositories

**Comment by rastersoft** [comment]
Ok... Tonight I'll rebuild the package using 16.04 repos (I made it using 15.10 ones). Hope to have it ready before 22:00 UTC.

**Comment by ElvisPresly** [comment]
Many thanks, it very cool

**Comment by rastersoft** [comment]
Ok, I uploaded the new packages for Ubuntu. Please, check them and tell me if everything works fine.

**Comment by ElvisPresly** [comment]
Download http://www.rastersoft.com/descargas/cronopete/cronopete-xenial_3.21.0-ubuntu1_amd64.deb

the same problem isn't enough dependence

**Comment by rastersoft** [comment]
Mmmm... Ok... I'll check it more deep.

**Comment by rastersoft** [comment]
By the way... it's not an uppercase 'O', but a zero...

**Comment by ElvisPresly** [comment]
doesn't find in repositories

**Comment by rastersoft** [comment]
Ok, now it should work... please, test it.

**Comment by ElvisPresly** [comment]
I don't know, there can be I download not that version, or at me something is broken. Still I see one and a touch a mistake.

**Comment by rastersoft** [comment]
Check that you are downloading package revision 2 (this is, the one that
ends in ubuntu2, not in ubuntu1).

El 29/04/16 a las 07:41, ElvisPresly escribió:
>
> I don't know, there can be I download not that version, or at me
> something is broken. Still I see one and a touch a mistake.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rastersoft/cronopete/issues/18#issuecomment-215631427>
>


-- 
Nos leemos
		             RASTER      (Linux user #228804)
sergio.costas@rastersoft.com        http://www.rastersoft.com

**Comment by rastersoft** [comment]
Also try to refresh the page. Sometimes I had problems with the browser
cache and my page (don't know why).

El 29/04/16 a las 07:41, ElvisPresly escribió:
>
> I don't know, there can be I download not that version, or at me
> something is broken. Still I see one and a touch a mistake.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rastersoft/cronopete/issues/18#issuecomment-215631427>
>


-- 
Nos leemos
		             RASTER      (Linux user #228804)
sergio.costas@rastersoft.com        http://www.rastersoft.com

**Comment by ElvisPresly** [comment]
yes I have cleaned cache the browser and have downloaded new audit, now everything is excellent. Thanks.

**Comment by ElvisPresly** [comment]
how to install Russian? I would like to complete the Russian localization to an ideal)

**Comment by rastersoft** [comment]
Just download the ru.po file, complete the translation, and send it to
be merged.

El 29/04/16 a las 10:03, ElvisPresly escribió:
>
> how to install Russian? I would like to complete the Russian
> localization to an ideal)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rastersoft/cronopete/issues/18#issuecomment-215653645>
>


-- 
Nos leemos
		             RASTER      (Linux user #228804)
sergio.costas@rastersoft.com        http://www.rastersoft.com

**Comment by ElvisPresly** [comment]
the translation is fully complete. I want to include localization in the program to fix small bugs. I need to see as it will look in the program interface that words and t of didn't move down.
