### ISSUE TITLE
Fedora rpm build issues

### ISSUE THREAD

**Issue by mann-ed** [rastersoft/cronopete#19]
I tried using the included spec file to build for Fedora 24 and it failed. I updated the spec file from one i had made myself for an earlier release. I was able to build and have cronopete running on my machine. Would you be interested in my updated spec? Should i submit a pull request? What preferred method would you like?

Well first would you even be interested in the changes?

Thanks

**Comment by mann-ed** [comment]
Name: cronopete
Version: 3.21.0
Release: 1
Summary: A backup utility for Linux.
License:        GPLv3
URL:            https://github.com/rastersoft/cronopete
Group:          System/Servers
Source:         %{name}-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root

BuildRequires: gcc
BuildRequires: gcc-c++
BuildRequires: vala
BuildRequires: glibc-headers
BuildRequires: libappindicator-gtk3-devel
BuildRequires: atk-devel
BuildRequires: cairo-devel
BuildRequires: gtk3-devel
BuildRequires: gdk-pixbuf2-devel
BuildRequires: libgee-devel
BuildRequires: glib2-devel
BuildRequires: gsl-devel
BuildRequires: pango-devel
BuildRequires: libudisks2-devel
BuildRequires: libX11-devel
BuildRequires: cmake
BuildRequires: gettext
BuildRequires: pkgconfig
BuildRequires: make
BuildRequires: intltool

Requires: libappindicator-gtk3
Requires: libdbusmenu
Requires: gtk3
Requires: pango
Requires: atk
Requires: cairo-gobject
Requires: cairo
Requires: gdk-pixbuf2
Requires: glib2
Requires: libgee
Requires: gsl
Requires: glibc-devel
Requires: libudisks2
Requires: libX11

%description
A backup utility for Linux.
.
Cronopete is a backup utility for Linux, modeled after Apple's Time
Machine. It aims to simplify the creation of periodic backups.
.

%prep
%setup -n %{name}-%{version}

%build
%cmake . -DCMAKE_INSTALL_LIBDIR:PATH=%{_libdir} \
-DLIB_INSTALL_DIR:PATH=%{_libdir} \
-DCMAKE_POSITION_INDEPENDENT_CODE=TRUE

make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot}

%clean
[ "%{buildroot}" != / ] && %{__rm} -rf "%{buildroot}"


%files
%defattr(-,root,root,-)
%{_datadir}/doc/cronopete/*
%doc README
%{_bindir}/*
%{_prefix}/lib/plugs/cronopete/*
%{_datadir}/cronopete/*
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/*
%{_datadir}/locale/*
%{_datadir}/dbus-1/services
%{_datadir}/glib-2.0
%{_sysconfdir}/xdg

%changelog
* Thu Jul 07 2016 Edward Mann <e.dev at edmann dot com> - 3.21.0-1
- Updating to 3.21.0

* Sat Apr 11 2015 Edward Mann <e.dev at edmann.com>
- Initial Spec build for Fedora

**Comment by q2dg** [comment]
There is already a Fedora 25 package available to download in official page (http://www.rastersoft.com/descargas/cronopete/cronopete.fedora25-3.26.1-2.x86_64.rpm) so I don't get the point of this issue
