### ISSUE TITLE
Massive flicker in restore app

### ISSUE THREAD

**Issue by stuaxo** [rastersoft/cronopete#25]
I installed cronopete, and made a backup.

When I opened the restore app it is flickering many times a second, which makes it impossible to use.

I'm on Ubuntu Xenial (16.10) 64 bit with gnome shell.

**Comment by rastersoft** [comment]
Does it stop flickering after one or two seconds, or it never stops?

**Comment by stuaxo** [comment]
I tried to start it just now, to test this and nothing happened.

Launching in the terminal, this message is displayed:

```
$ cronopete_restore.sh
method return time=1489011288.854599 sender=:1.747 -> destination=:1.1543 serial=597 reply_serial=2
```

**Comment by stuaxo** [comment]
Any idea why it is not launching at all now ?

Could it be because the disk I backed up on is not plugged in ?

**Comment by rastersoft** [comment]
Wha... Well, obviously, if you don't have the backup disk plugged, it is impossible to open the list of backups...

**Comment by rastersoft** [comment]
But maybe adding an alert message would be a good idea...

**Comment by stuaxo** [comment]
Ideally, there would be something like the ordinary gui, with an overlay with a message, then on attaching the media things would start normally.

But yeah, at a minimum, a message would be more user friendly.

I'll dig out the disk and see what happens wrt flicker.

**Comment by stuaxo** [comment]
Hi,
   Finally dug out the hard disk with the backup on it and re-ran cronopete.

I've left it going for about 5 minutes and it hasn't stopped flickering.

Here is a video  https://www.youtube.com/watch?v=L5xT_kwkGlc&feature=youtu.be

**Comment by stuaxo** [comment]
Update:  Just ran this again and now there are two backups it doesn't flicker.
