### ISSUE TITLE
feature request: backup on internal disk

### ISSUE THREAD

**Issue by fred06** [rastersoft/cronopete#29]
Hi,

I would like to backup my data on a second internal drive, not a usb one.

could you please add this feature in a future release ?

thanx, 

-- Frederic

**Comment by rastersoft** [comment]
Hi:

You can: just check the option "show all disks" when choosing the disk 
where to do the backup.

**Comment by fred06** [comment]
sorry, even with the "show all disks" checked, the window titled "avalable usb disks:" remains empty.

my OS: ubuntu 17.04

**Comment by rastersoft** [comment]
Hi:

Remember that cronopete mandates to use a different PHYSICAL disk than 
the one that contains the HOME folder. It is not valid to have two 
partitions in the same disk and do backup from one partition to another.

Doing a backup to the same physical disk is absurd, because if the disk 
fails, you loose both the original data and the backup.

**Comment by fred06** [comment]
Hi,

i fully agree with you ... in fact, there was a syntax error in my /etc/fstab, that is why my second physical disk was not mounted. It has been corrected, and so I now have a /dev/sdb1 partition mounted on /data:

```
mount|grep sd
/dev/sda2 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/sda3 on /othersys type ext4 (rw,relatime,data=ordered)
/dev/sda4 on /home type ext4 (rw,relatime,data=ordered)
/dev/sdb1 on /data type ext4 (rw,relatime,data=ordered)
```
... but las, this second drive does still not appear in the proposed backup drives window.

**Comment by rastersoft** [comment]
Which linux distro are you using? These last days Debian SID had a bug that prevented mounting external drives, and in my system cronopete was unable to find the external disk. Now it has been fixed, but you must update the packages and reboot.

**Comment by rastersoft** [comment]
Mmmm... You say your /etc/fstab...

That could be the reason: AFAIK, drives available in the fstab are considered fixed drives. Remove it and let cronopete manage the automatic mounting operations.

**Comment by rastersoft** [comment]
So? Did removing it from fstab do the trick?

**Comment by fred06** [comment]
at first, my second drive was not listed in the /etc/fstab file ... and was not mounted by cronopete anyway.

I'm using ubuntu 17.04.

Are there some logs from cronopete somewhere ? /var/log/kern.log tells me nothing.

**Comment by rastersoft** [comment]
Mmm...

When you open the file manager, is your disk available to be mounted like any other disk?

If not, try to go to the BIOS and configure as "removable" the SATA port where your internal disk is connected.
