### ISSUE TITLE
Switching between two disk

### ISSUE THREAD

**Issue by maieul** [rastersoft/cronopete#31]
I have two backup disks: one at home, the other one at office. Is it possible to switch between them?

**Comment by rastersoft** [comment]
Currently it is not possible... but it is a good idea.

**Comment by maieul** [comment]
ok. I will use an othetr backup tool for the second one. But I think that will be a very good practice.

**Comment by maieul** [comment]
Note that is is currently working if we switch manually between the two disks in the setting.

**Comment by rastersoft** [comment]
I know, but that is not a good solution :D

**Comment by rastersoft** [comment]
I'll try to add support for this in the new version.

**Comment by rastersoft** [comment]
I've been trying to implement this, but there are a lot of corner cases, so I think I won't be able to add it to cronopete and keep it fully safe and functional.

But... there is a possibility: cronopete uses the partition UUID to detect the backup disk, so you can change the partition uuid in the office's disk, with the same value from the disk in your home.

Here are some instructions http://www.sudo-juice.com/how-to-change-the-uuid-of-a-linux-partition/

**Comment by maieul** [comment]
Thnak for this message.
I think I will kept my actual technic, which is slower but don't go
inside the "linux wizardly"

**Comment by rastersoft** [comment]
Ok. Anyway, I hope to add a "folder backend", and that should allow you to do the backups in an easier way.
