### ISSUE TITLE
Support for Fedora 27

### ISSUE THREAD

**Issue by zer09** [rastersoft/cronopete#32]
Can't install cronopete in Fedora 27 because of the old gsl package.

Thanks.

**Comment by rastersoft** [comment]
I'm preparing a new RPM package.

**Comment by rastersoft** [comment]
Uploaded the new RPM package for Fedora 27. Please, try it.

**Comment by zer09** [comment]
Sorry, but I am not able to find the new RPM package on your website. It is still the old version.

**Comment by rastersoft** [comment]
Refresh the page. Also, go directly to "programs->cronopete". The main page doesn't show an announce about this because it is just a repackage.

**Comment by zer09** [comment]
Thank you so much!
