### ISSUE TITLE
Deleted old backup after having made the new one

### ISSUE THREAD

**Issue by maieul** [rastersoft/cronopete#33]
Hi,

actually, when we start a backup, cronopete first delete old backup, when start the new one. I think the order should be the other one:
- sometime, we have just time to make backup before living office, and we don't want to lose time with cleaning
- if there is a problem in the new backup, we lost what was cleaned.

**Comment by rastersoft** [comment]
I'm doing a big code refactorization in cronopete, and this is one thing I added in the new version. You can test it, but keep in mind that it is still a work-in-progress. It is in the "rsync" branch.

**Comment by rastersoft** [comment]
The new version (in the RSYNC branch) implements this, so I'll close it.
