### ISSUE TITLE
Pango Warning : invalid UTF-8

### ISSUE THREAD

**Issue by MisterT2** [rastersoft/cronopete#34]
Hi,
I have this message (warning message) poping up regularly on my cronopete instance:
`(cronopete:8432): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()`

I'm running Ubuntu 14.04.5 LTS
Pango libraries installed:
> ii  libcogl-pango15:amd64                                       1.16.2-1                                            amd64        Object oriented GL/GLES Abstraction/Utility Layer
ii  libpango-1.0-0:amd64                                        1.36.3-1ubuntu1.1                                   amd64        Layout and rendering of internationalized text
ii  libpango-1.0-0:i386                                         1.36.3-1ubuntu1.1                                   i386         Layout and rendering of internationalized text
ii  libpango-perl                                               1.224-2                                             amd64        Perl module to layout and render international text
ii  libpango1.0-0:amd64                                         1.36.3-1ubuntu1.1                                   amd64        Layout and rendering of internationalized text
ii  libpango1.0-0:i386                                          1.36.3-1ubuntu1.1                                   i386         Layout and rendering of internationalized text
ii  libpango1.0-dev                                             1.36.3-1ubuntu1.1                                   amd64        Development files for the Pango
ii  libpangocairo-1.0-0:amd64                                   1.36.3-1ubuntu1.1                                   amd64        Layout and rendering of internationalized text
ii  libpangocairo-1.0-0:i386                                    1.36.3-1ubuntu1.1                                   i386         Layout and rendering of internationalized text
ii  libpangoft2-1.0-0:amd64                                     1.36.3-1ubuntu1.1                                   amd64        Layout and rendering of internationalized text
ii  libpangoft2-1.0-0:i386                                      1.36.3-1ubuntu1.1                                   i386         Layout and rendering of internationalized text
ii  libpangomm-1.4-1:amd64                                      2.34.0-1ubuntu1                                     amd64        C++ Wrapper for pango (shared libraries)
ii  libpangox-1.0-0:amd64                                       0.0.2-4ubuntu1                                      amd64        pango library X backend
ii  libpangox-1.0-0:i386                                        0.0.2-4ubuntu1                                      i386         pango library X backend
ii  libpangoxft-1.0-0:amd64                                     1.36.3-1ubuntu1.1                                   amd64        Layout and rendering of internationalized text
ii  libpangoxft-1.0-0:i386                                      1.36.3-1ubuntu1.1                                   i386         Layout and rendering of internationalized text

Nothing critical ! 
This is just a warning...

Thanks for your excellent program !

**Comment by rastersoft** [comment]
14.04? A bit old...

**Comment by MisterT2** [comment]
Well... not for me ! :-)
If you think the issue is related to this Ubuntu version, no problem. As I said, that's absolutely not critical, but I thought it could be useful to share it with you in case it was underlying something more serious...
Thanks again

**Comment by rastersoft** [comment]
You are welcome :)
