### ISSUE TITLE
Request: file size limit

### ISSUE THREAD

**Issue by zer09** [rastersoft/cronopete#36]
Can we add option, that will not backup if file reach certain file size?

Example use case, is that you copy a large file temporarily to your home directory or desktop, that you will delete later, and that file should not be backup.

**Comment by rastersoft** [comment]
It is better to have an specific folder for that files, and put that folder in the "Exclude" list. Because it is easy to have other files as large or more than that without knowing, and discover too late that they aren't backed up...
