### ISSUE TITLE
Stopping backup does not work

### ISSUE THREAD

**Issue by maieul** [rastersoft/cronopete#37]
When cronopete is currently deleting older backup, the "stop backup" option does not work.

**Comment by rastersoft** [comment]
I'm preparing a big new version of cronopete, with a lot of code refactorization, and this problem will (hopefully) be gone. You can test it if you want in the "rsync" branch. It should work fine, but it is still work-in-progress.

**Comment by rastersoft** [comment]
The version in the RSYNC branch should work now. Can you test it, please?

**Comment by maieul** [comment]
Not before saturday

**Comment by maieul** [comment]
And how could I do? I have never installed programm without ppa/ubuntu package

**Comment by rastersoft** [comment]
Ooops... Ok, sorry, I presumed that you had knowledge about compiling, since you have a github account O:)

**Comment by rastersoft** [comment]
(I always forget that you can use github for more than coding)

**Comment by maieul** [comment]
I code, but only for python/latex, but i see you have a makefile. so it could be ok. the only problem I have is about where I should put the bin without breakin my installation.

**Comment by rastersoft** [comment]
Mmm... better wait... I'll create a deb package. Which ubuntu version do you use?

**Comment by maieul** [comment]
16.04 tls

**Comment by maieul** [comment]
lts not tls

**Comment by rastersoft** [comment]
You can find the at:
http://www.rastersoft.com/cronopete_xenial_3.99.0-ubuntu1_i386.deb
http://www.rastersoft.com/cronopete_xenial_3.99.0-ubuntu1_amd64.deb

**Comment by maieul** [comment]
I will try it his week-end, I hope. But i have many thing to do, and I can't ensure you.

**Comment by rastersoft** [comment]
There is no hurry. But remember that it is still a work-in-progress.

**Comment by rastersoft** [comment]
BTW: just updated the packages to the last version, which add several new things, like the new timeline. If you prefer to test this one...

http://www.rastersoft.com/cronopete-xenial_3.99.2-ubuntu1_i386.deb
http://www.rastersoft.com/cronopete-xenial_3.99.2-ubuntu1_amd64.deb

**Comment by maieul** [comment]
unfortunatly, I dind't find the time to test this week-end, and I won't
have it before a month, as I am doing a long trip

**Comment by rastersoft** [comment]
No problem.

**Comment by rastersoft** [comment]
New 4.0 version should fix this.
