### ISSUE TITLE
Cronopete in French

### ISSUE THREAD

**Issue by maieul** [rastersoft/cronopete#38]
Hi,

the interface of cronopete mix French and English. It is very strange. If you explain me, I could translate remaining localization string. 

ps : thanks for the new version.  Is there a way to send you some money?

**Comment by rastersoft** [comment]
That's because I changed and added some sentences in the new version. To fix this, just edit the file po/fr.po (I recommend you to use a .po editor, like gtranslator, poedit or lokalize), send it to me, and I will add it to the packages.

**Comment by rastersoft** [comment]
About money, don't worry. I prefer to not charge for my programs.
