### ISSUE TITLE
Cannot remove external drive

### ISSUE THREAD

**Issue by fezgit** [rastersoft/cronopete#41]
Hello!

I just started using Cronopete and it seems to check all my backup needs. The only inconvenient aspect when backing up to an external hard drive connected via USB is that Cronopete insists on remounting the drive every time, which makes it impossible to safely remove the drive. Right now I have two options: either I turn backups on and off every time I connect the drive (which seems rather inconvenient) or I kill Cronopete (which seems rather unclean).

I should say I am on Debian testing.

Thanks!

**Comment by rastersoft** [comment]
Hello:

Yes, it is done that way to ensure that accidentally unmounting the drive doesn't disable the backups. The idea with Cronopete is to keep it doing backups regularly, so you should never disconnect the drive.

I just have an USB drive permanently connected to the computer and doing backups there, but in a place where it is easy to take and remove in case I have to "take the most important and run" (let's say, an earthquake or a fire in the building).

**Comment by fezgit** [comment]
Thank you for the quick reply.

I see the appeal when using Cronopete with a desktop computer but, in the case of a laptop, a permanently connected external drive is unlikely. Perhaps then it would be good to include an option in Cronopete to enable/disable automatic drive remounting.

Thanks!

**Comment by rastersoft** [comment]
Mmm... I see your point. I will think something.

**Comment by rastersoft** [comment]
I uploaded a change into "master" that allows to unmount the disk from cronopete itself. This keeps the security of avoid accidental unmount from a file manager, but allowing to unmount it manually.

When unmounted, you can remove it, and as soon as it is connected again it will be mounted automatically again. The same if you don't disconnect it but mount it again: it will be mounted automatically again until you unmount it from cronopete again.

You can unmount the disk both from the icon in the taskbar, and from the configuration window (just in case you use gnome shell and don't use an appindicator/kstatusnotifier extension).

Please, test it and tell me any change that you think I should add.

**Comment by rastersoft** [comment]
Added an extra change: now, if it can't unmount the disk (because another process is using it) will show an error.

**Comment by rastersoft** [comment]
Yes, with a clone you will have all the sources. Then, just create an "install" folder, get inside, type

cmake ..
make
sudo make install

et voila :)

**Comment by fezgit** [comment]
Thank you very much!

I compiled, installed and everything works great, including the new option to unmount from within Cronopete.
