### ISSUE TITLE
build error - restore_canvas.vala:757.32-757.58: error: The name `abs' does not exist in the context of `double'

### ISSUE THREAD

**Issue by staubenheimprobst** [rastersoft/cronopete#43]
Hello, 
i have a build error. I didn't find the failure. I would like testing my new .po.

cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'gtk+-3.0;appindicator3-0.1;cairo;gdk-3.0;gdk-pixbuf-2.0;gee-0.8;gio-2.0;glib-2.0;gobject-2.0;gsl;pango;pangocairo;udisks2'
--   Found gtk+-3.0, version 3.18.9
--   Found appindicator3-0.1, version 12.10.0
--   Found cairo, version 1.14.6
--   Found gdk-3.0, version 3.18.9
--   Found gdk-pixbuf-2.0, version 2.32.2
--   Found gee-0.8, version 0.18.0
--   Found gio-2.0, version 2.48.2
--   Found glib-2.0, version 2.48.2
--   Found gobject-2.0, version 2.48.2
--   Found gsl, version 2.1
--   Found pango, version 1.38.1
--   Found pangocairo, version 1.38.1
--   Found udisks2, version 2.1.7
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- Found Vala: /usr/bin/valac  
-- checking for Vala version of valac-0.30
--   found Vala, version 0.30
-- Found Vala: valac-0.30  
-- Configuring done
-- Generating done
-- Build files have been written to: cronopete/BUILD

cronopete/BUILD $ make
Scanning dependencies of target i18n
[  0%] Built target i18n
[  6%] Generating cronopete/BUILD/src/Config.c;backup_base.c;backup_folder.c;backup_rsync.c;choose_disk.c;cronopete.c;fixedlabel.c;helpers.c;icons_widget.c;menu.c;options.c;restore.c;restore_canvas.c
cronopete/src/restore_canvas.vala:757.32-757.58: error: The name `abs' does not exist in the context of `double'
					if ((element == null) || ((event.y - backup.ypos).abs() < distance)) {
					                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cronopete/src/restore_canvas.vala:760.20-760.46: error: The name `abs' does not exist in the context of `double'
						distance   = (event.y - backup.ypos).abs();
						             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)
src/CMakeFiles/cronopete.dir/build.make:112: die Regel für Ziel „src/cronopete_valac.stamp“ scheiterte
make[2]: *** [src/cronopete_valac.stamp] Fehler 1
CMakeFiles/Makefile2:281: die Regel für Ziel „src/CMakeFiles/cronopete.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/cronopete.dir/all] Fehler 2
Makefile:138: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

Best Regards
Steffen

**Comment by rastersoft** [comment]
I suspect you have an old version of the Vala compiler. Are you still using Ubuntu 16.04 or a derived distro?

**Comment by staubenheimprobst** [comment]
Yes. I'm use Mint 18.1. I thin it is a Ubuntu 16.04.

valac --version
Vala 0.30.1

Best Regards

**Comment by rastersoft** [comment]
That's the problem: your vala compiler is too old, because support for abs method in floats was added in 0.32 or so, I think.

Anyway, according to the wikipedia, in a couple of weeks Linux Mint 19 "Tara" will be launched, and it will fix this.

**Comment by staubenheimprobst** [comment]
Thx. This is the solution.
I found a vala repo for ubuntu.
https://launchpad.net/~vala-team/+archive/ubuntu/ppa
