### ISSUE TITLE
[Suggestion] Cronopete should warn, not hinder

### ISSUE THREAD

**Issue by robohobbit** [rastersoft/cronopete#50]
I want to use Cronopete to make a backup in a folder that gets syncronised with a cloud service. However, the software notifies me that it is bad practice and that if I don't know how to use gconf I shouldn't be using this option.

This sounds a little patronising and it discouraged me from using the software. I don't use Gnome. I don't know how to use gconftool and I'm not interested in using it, but I know that the backup would be safely uploaded in the cloud.

I'm okay with the program reminding me that a same-drive backup could be risky, but it should limit itself to warning the user.

**Comment by funilrys** [comment]
@robohobbit it's not explicitly said - and I do not understand why - but @rastersoft moved the work based logic to [GitLab](https://gitlab.com/rastersoft/cronopete) ...

**Comment by robohobbit** [comment]
Okay, thanks. I'll open an issue there.
