### ISSUE TITLE
No backup disks recognised on debian 9.5

### ISSUE THREAD

**Issue by fatherseye** [rastersoft/cronopete#51]
Hi. 
Having used timemachine and finding it nice to use, I was very excited to find cronopete for linux backups. However, I'm having some trouble. I downloaded the stretch 64 bit debian package (4.5.0) and installed it using dpkg. It installed ok and started up giving me the red circle item on the little tab at the bottom left of the screen. I can even select the "configure the backup" menu item. When I click the 'change destination...' button I get an "Available USB Disks" dialog with no disks. I have tried plugging in a western digital USB3 disk formatted with GID and a single ext3 partition. I tried mounting it, unmounting it, clearing the formatted partition. I've tried starting cronopete before and after plugging in the disk. Cronopete still doesn't see the disk. I've also toggled the "Show all disks (except /home) option which makes no difference. 

/var/log/messages contains the following references to conopete
```
Aug 22 16:33:30 lappie gnome-software-service.desktop[25195]: 04:33:30:0974 As  failed to rescan: Failed to parse /usr/share/applications/cronopete_preferences.desktop file: cannot process file of type application/x-desktop
Aug 22 16:33:30 lappie gnome-software-service.desktop[25195]: 04:33:30:0978 As  failed to rescan: Failed to parse /usr/share/applications/cronopete_restore.desktop file: cannot process file of type application/x-desktop
Aug 22 16:33:39 lappie cronopete[30795]: GtkDialog mapped without a transient parent. This is discouraged.
Aug 22 16:33:54 lappie cronopete_preferences.desktop[30790]: method return time=1534912434.942124 sender=:1.80 -> destination=:1.79 serial=23 reply_serial=2
Aug 22 16:33:55 lappie cronopete[30795]: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Aug 22 16:34:32 lappie cronopete[30795]: g_variant_get_variant: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_VARIANT)' failed
Aug 22 16:42:37 lappie cronopete[3275]: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Aug 22 16:43:50 lappie cronopete[3275]: g_variant_get_variant: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_VARIANT)' failed
Aug 22 16:43:50 lappie cronopete[3275]: g_variant_get_variant: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_VARIANT)' failed'
```
I assume I'm doing something wrong. Could you please point me in the right direction?

**Comment by rastersoft** [comment]
Hi:
Do you have udisks2 installed?

**Comment by fatherseye** [comment]
Yes. Is this it?
```
user@pc:~$ dpkg-query -s udisks2
Package: udisks2
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 2011
Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: foreign
Version: 2.1.8-1
...
```
When I ran `udisksctl status` the backup disk showed up as sdb. Unfortunately I don't have an external disk with me at the moment so can't provide output.

**Comment by rastersoft** [comment]
Can you put your /etc/udisks2/udisks2.conf file?

**Comment by rastersoft** [comment]
(another user with KDE had the same problem... it's odd)

**Comment by fatherseye** [comment]
The directory /etc/udisks2 exists but is empty.

**Comment by rastersoft** [comment]
Mmmm... Interesting...

This is my udisks2.conf file. Try to copy it, and reload udisks2 with `sudo systemctl restart udisks2.service`

```
[udisks2]
# Comma separated list of modules to load.
# Use asterisk to load all the modules.
modules=*
# Valid options are 'ondemand' or 'onstartup'.
modules_load_preference=ondemand
```

**Comment by fatherseye** [comment]
Still nothing. The only disk I have with me is a fat32 formatted usb2 disk but that doesn't show up still.

The disk mounts when I plug it in.

**Comment by fatherseye** [comment]
```
root@lappie:/etc/udisks2# systemctl restart udisks2.service
root@lappie:/etc/udisks2# cat udisks2.conf 
[udisks2]
# Comma separated list of modules to load.
# Use asterisk to load all the modules.
modules=*
# Valid options are 'ondemand' or 'onstartup'.
modules_load_preference=ondemand

root@pc:/etc/udisks2# udisksctl status
MODEL                     REVISION  SERIAL               DEVICE
--------------------------------------------------------------------------
SanDisk SD5SG2128G1052E   10.04.01  135293417348         sda     
WDC WD16 00BEVE-00A0HT0   0811      WDC_WD16_00BEVE-00A0HT0-0:0 sdb     
```

**Comment by rastersoft** [comment]
do a 'killall cronopete', relaunch udisks2, and try again. Just in case...

**Comment by fatherseye** [comment]
Sorry. No change.

**Comment by fatherseye** [comment]
```
root@lappie:/etc/udisks2# killall cronopete
root@lappie:/etc/udisks2# systemctl restart udisks2.service
root@lappie:/etc/udisks2# cronopete

(cronopete:8343): GLib-CRITICAL **: g_variant_get_variant: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_VARIANT)' failed

(cronopete:8343): GLib-CRITICAL **: g_variant_get_variant: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_VARIANT)' failed

(cronopete:8343): GLib-CRITICAL **: g_variant_get_variant: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_VARIANT)' failed
```

**Comment by rastersoft** [comment]
Oh, wait... I'll check the API I'm using, just in case I'm using a call that wasn't implemented in that version of udisks2... It is stretch, the stable Debian, so that udisks2 can be a little old...

**Comment by fatherseye** [comment]
Sergio, Thanks very much for taking the time to look into this. Unfortunately its getting late here now so I'm going to have to shut down for the night.

Cheers.

**Comment by rastersoft** [comment]
Don't worry. I'll install a debian in a virtual machine and try it.

**Comment by rastersoft** [comment]
Ok, I found the problem: there is a language capability from Vala that is supported from version 0.36, but Debian Stretch comes with Vala 0.34. Unfortunately it doesn't fail to compile, but the resulting code doesn't work.

It seems you can't use cronopete with stretch... sorry.
