### ISSUE TITLE
Running on Solus

### ISSUE THREAD

**Issue by fabioda** [rastersoft/cronopete#53]
Hi.  I used to use cronopete successfully in both Antergos and PopOS Linux versions.  I just switched to Solus, and, since the package is not available, I built it from source.
I cannot run it without root privileges, and when I try I get the following error:

(cronopete:1848): GLib-GIO-ERROR **: 22:34:46.012: Settings schema 'org.rastersoft.cronopete' is not installed

Is this an installation issue?

**Comment by rastersoft** [comment]
Please, go to gitlab. That is the official repository.
